---
cluster_name: diplom-cluster

# RBAC
authorization_modes:
  - Node
  - RBAC

# Шифрование secrets через KMS
# kube_encrypt_secret_data: true

# kubeconfig для внешнего доступа
kubeconfig_localhost: true
kubectl_localhost: true

supplementary_addresses_in_ssl_keys:
  - "158.160.59.64"
